name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congrats on your first issue. Welcome to the team **#**, our bugs are your bugs now!"
        pr-message: "ERROR: EVERYTHING IS BROKEN! Just kidding, first pull request in the books, noice."
