name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Mischief managed! Nice job **#**"
        pr-message: "ERROR: EVERYTHING IS BROKEN! Just kidding, first pull in the books, noice."
