# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 09 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 10
        stale-issue-message: "Please return this issue to the fridge, it's getting stale"
        stale-pr-message: "Please return this pull request to the fridge, it's getting stale"
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        close-issue-label: 'Closed due to staleness, feel free to freshen up if necessary'
        close-pr-message: 'Closed due to staleness, feel free to freshen up if necessary'
